### PR TITLE
#396 Fix for the issue #396

### LINKED ISSUE #396: Kall mot GET /storage/api/v1/instances?org=dmf&size=50  og header X-Ai-InstanceOwnerIdentifier filtrerer ikke resultatet
### Description of the bug

jeg forsøker å hente ut alle instanser for en part basert på org nr:
GET /storage/api/v1/instances?org=dmf&size=50

X-Ai-InstanceOwnerIdentifier: ***
Der jeg har forsøkt å erstatte *** med "<orgnr>" , og "Organisation:<orgnr>".

Jeg får alltid alle skjema fra _alle_ parter, men forventer å bare å få instanser fra _gitt org_. 

I dokumentasjonen står det beskrevet at med gitt header skal svaret være filtrert.
Screenshot 2024-05-03 at 10 14 25

Workaround er å laste ned alle instanser for alle apper, og så filtrere på klientsiden.

### Steps To Reproduce

Gjør et kall:
GET /storage/api/v1/instances?org=dmf

X-Ai-InstanceOwnerIdentifier: <orgnr>

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by codemascot**
Moved conditional later to fix #396

## Description
Moved conditional later to fix #396 

## Related Issue(s)
- #3 
- #396

## Verification
- [x] **Your** code builds clean without any errors or warnings
- [ ] Manual testing done (required)
- [x] All tests run green

### CODE REVIEW

File: src/Storage/Controllers/InstancesController.cs [hunk 1]
```diff
@@ -141,51 +141,53 @@ public class InstancesController : ControllerBase
...
-                }
+                case (false, true):
+                    break;
+
+                default:
+                    return BadRequest();
             }
-            else
+
+            if (instanceOwnerPartyId == null)
```
Comment (SandGrainOne) [inline src/Storage/Controllers/InstancesController.cs:174]: Instance owner party id is required only for end users. If the caller is org, then instance owner is optional.

File: src/Storage/Controllers/InstancesController.cs [hunk 2]
```diff
@@ -141,51 +141,53 @@ public class InstancesController : ControllerBase
                 return BadRequest("Both InstanceOwner.PartyId and InstanceOwnerIdentifier cannot be present at the same time.");
             }
 
-            if (orgClaim != null)
+            switch ((orgClaim != null, userId != null))
```
Comment (acn-sbuad) [inline src/Storage/Controllers/InstancesController.cs:144]: I think the if statements are easier to make sense of compared to the switch. What motivated the change?

Comment (SandGrainOne) [inline src/Storage/Controllers/InstancesController.cs:144]: I'm not sure turning the if into a switch was necessary. I would revert this.

Comment (SandGrainOne) [reply src/Storage/Controllers/InstancesController.cs:144]: As we talked about. Instead of if-else do separate tests for different cases and exit early.

```
if (orgclaim is null and userid is null {
   return BadRequest()
}

If (orgClaim is not null) {
   validate and handle required parameters for org
}

Perform party "normalization"

If (user is not null) {
   validate and handle required parameters for user
}
```

**Review by acn-sbuad — APPROVED** [review]
🎈
